### ISSUE TITLE
CI failling due to deprecated `jax.ops.index_update`

### ISSUE THREAD

**Issue by wangleiphy** [fermiflow/CoulombGas#5]
currently CI is failing 
https://github.com/fermiflow/CoulombGas/runs/5611973129?check_suite_focus=true

This is probably due to an update in jax 0.3.2, https://jax.readthedocs.io/en/latest/changelog.html

>The functions jax.ops.index_update, jax.ops.index_add, which were deprecated in 0.2.22, have been removed. Please use [the .at property on JAX arrays](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html) instead, e.g., x.at[idx].set(y).

Please fix.

**Comment by buwantaiji** [comment]
Fixed. Thanks!
